name: tests

on:
  push:
    branches: []
  pull_request:
    branches: [main]

jobs:
  rust:
    name: rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo test
        working-directory: src/rust
        run: cargo test --all-features
